FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY frontend/package*.json ./
RUN npm install

COPY frontend .

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start", "--", "-p", "3000"]
